replicaCount: 1

appPort: 5000

image:
  registry: 288761732111.dkr.ecr.us-east-1.amazonaws.com/restapi-ecr
  tag: latest

environmentVariables: []
#   - name: FLASK_ENV
#     value: development

environmentVariablesFrom:
  - secretRef:
      name: mongodb-credentials

livenessProbe: {}

readinessProbe: {}

ingress:
  enabled: true

mongo:
  database: AgAUGBbtfG5kCDRDNBfur+UGLooby5zxoe5KuS3PUrjLQidk+hx3ZM7/h3iDDl6pnFXMHpFxVnW8x33/itv92bsMcgOrAIJG6DTpL+FbI6SuQcy7qtn9/KrA+z7SBd+1BAlS8Q5fvH/K9tjgtQtH263fCqIISmaGSX6T9B6SA3LYtzvQSIQU3ac38/BqFXR6nPBmRxOvsQAGImbdY06waLK3chLuvh8tN1tHM5En2UPh5BiEmNLKQ8MZNVnPnr7mb9oB5l8L6NHwZqcBe483BRd5kmUbkQT2ijJBRxAXaejTlN+zc/eCzeI3y+Jj/FYln6rPW8dNuKmvXFJ2aR+uMYXF/0UM1DJwplAH7l/zM3Ph7COJxLFlwUJAkZ2ZZQGm+Fg/8qELMvdtjlKYicfteQ/AqN7pF4uvu2z0bXiFODI2oCuVXa9nQFhwCJzIsWA8Ok4nkDQTBgfvPnt1B2Vo/bejWU3RNvF17JZ9WuyuJOrfGUsH65DXL4tFRsS3pE5kgxgEY85qVfF+b+h9YXvVCl9B+Z8DAOIcciayCXHav/3FNZtE84VLsViK1ynXcmh+hAYctY5g9SDMKtcV381WmkJ+MOZmjRPNMcMc+5Ih9TJ0LMgYfd1k1nQz/l04LvmvNeQZovqG8qplKyBxpSrgH/EDk3wg+ZftcA39IlTaNP8SgmLnHmFZrx/4UE+7xtXYzBK7Xbr6wg==
  host: AgA/WIzpDXYWSQgI6zq6YWgtqmbBweVNwEdGYNh+Kfn8+EvYf8bGPpQcgryy+J33SZ42enkBpMUNC2SVPcRJ6zBw/aM9bICtFr4+w0sfC5KW1/Euhd5cBh/TCbbvAx401seB/g+eNkDB8gkVLAMQw28IpSM4axlreIUZ4V8tK2+VxQZzGPIRL2hWkiDQW3a8JROoeYJ6tK5+R0LH8gwPjDtm64FjkHcdaX+TXRnd77UGOgptyD7H7uiZigISHqw+QaqzGP3z/HHbSIgkxP/rndJBr7kvND5mOFpCclPUEbXvkuhOexKluSilUef+7/zQpXV0JHkyBPaINgPkEa+ZDM2vm7cweMAdqO/7nDPxivMYoMvpXYMFRRs2U9O+E2Hdahzd6sd0gLqp42/KVkQdaWLMF/nP/i6pu8okwnW6iuiJSCRnRrN4omx7fm4AWaQevndiOxt7fSiQfgUDqyjrAO2ayDd8TBB0KYOk9d6S6SJKsw0pAuFXtT0/dn0OaSYlZ5+bZsYiHd3sk3A/DlZfBMp15pJgD84qxTriYOyn/sM++yGx7BX4UUzGXMa4kDUwNhm85EQ7jDNtte95iihWfYnhC7NSpMTVr6NP1x06GpJAraELUlP0QS8DiBpJTvU4/ydm1qEYCfWef1+CIuVpyQJhyBnnunitHdRSccCyvgTg+ypSAyUnpr5hOEnzR2Rj0fX5D56TV0mtjZo7EA==
  password: AgCKZ0vYsoe1FIBIIFLEp3eqonxZPbaW3umuys0fyPH2Ze0JmSDKIcRiTDgNzT8QQWFF/faxfIZzwHP8U7skxxw5me6YFbBHVqW5XeBAd12CDSi6kLcCANq6pfxAK99iH7YfnhiJP+tKqwlQJtK/FAZ5LKy7TfPFACnP3FRjFQJDQMD1iSNkrP8jOn1jzRLEO7zCtNM90BGjjLieveD0Rfp/RwBU3i6OkrBeYC/wdpWqC88NM5KZsN5x54UwZZADJN4h3Fn0cVP9vDmqRZX9lEgsmPobNuW+6Zzq2WP1xIB13KMfsisBshllwJfOg0L0ndkVRW9RdR6Y3JigMYQpA43kRKlIk7avgn6phLODFa7G46ri8XeM0Xbd5aQQlixaz0Oykj9LgJ+xVBTUI4mgfaj9nXKVY41RPPAKm/9gU+61KsIcgL7wJyX2UWIeyu3EKAtm4ZTPFGY1BVeEfu8XRhHe81T2sTpMPFpQa7TVGIlTIPUdeD/xWK+d+b2arCkS62Wgfn+k4xDURWW73G3En1BA+y17dSTsqIoa61ugMgFr1CbxjV7wjxqOZ6yw3lTFODtB2mO+MkvRSctlFMeHuGw6DXQz+UkoCPR5wN0GHoqL2oLEeUeCq4+Oo3XsBpf7uGlkTWpN1J1xcPPFwuhfFj24F3O/Xj0SCK923boyw9a62IIN+1d9NXoLiDNeJE5hAB+OfUb4a5/AsmiKDAAUhaBAbg==
  user: AgA37GyYPB9L+NY198Hj1Oz5xo/pjLNbW7LMkhVdmizkm+r/UTwT2DnBKUBkLCbOv2Mu/WL827F14/IK3YOmrp/R4fs8FpT/WR0Gz32m3gOJvk0v/QzJz0NNcaSuY0L9Z1qkc1kz5WnuveZN76tQeKXJSd5M5aRXxSrXuXLNCd7kQdouNQoQ+idjukgioqtMpwumML7rC939e5W7Hpnxr1M+eZMYy7el86Muj/rAjzDNSjNsDVrHX4cRScyWh5sSefW6A9ovAdQ31/C+lsEOnE+eTB4Kz9z7bNJyegP50K9/Zr6RDTduayh9P+cJIaygHfHFn9WqfLp1+Qc13I9WVWBqwm1s0LmVQFTZt607m1wrNjshx+ZYVDhOM35SU4csAflW54Nlk1/TPU3UAT1+DvTRl8GWV+Fh3RsJHIMxTy+lecPcFy5EkRNYq69Z7gLoS+myRgs/Y54QEIdok1nCMyVL8rd9io7SbRqk7eHXwYfh08mj79ssBxHtI0rIbOleUTVsTvsZQ8otpnmGUTz8roZkxCfOFw6oQTe9ZG6Y4xQevnnpDGnGqOL6Ia+SlvRM8qkerXDmn5XzDbB+oXpoMKYI2+/BcejeX20hpQV7xLexk/epxG0exatNsnQeXAK1ZrcW9IAE/WraCxeNYbApZw2sxHvuyeflPVDHyvEl3IXBzG6KSaGyW6VUex+yg034Lj0yvSVwE/eY