- hosts: mongodb
  become: yes
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        name: python3-pip
        state: present
    - name: Install pymongo
      pip:
        name: pymongo
  vars:
    mongodb_version: 8.0
    debian_packages: []
    replicaset: false
  vars_files:
    - vars.yml
  roles:
    - community.mongodb.mongodb_linux
    - community.mongodb.mongodb_repository
    - community.mongodb.mongodb_install
    - community.mongodb.mongodb_mongod
    - mongodb_patch
    - community.mongodb.mongodb_auth